export const styles = {
  app: {
    display: "flex",
    minHeight: "100vh",
    background: "#f4f6fb",
    fontFamily: "Arial, sans-serif",
  },
  sidebar: {
    background: "#0d224f",
    color: "white",
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    transition: "0.3s",
  },
  collapseBtn: {
    display: "flex",
    justifyContent: "flex-end",
  },
  btn: {
    background: "transparent",
    border: "none",
    color: "white",
    cursor: "pointer",
  },
  logo: {
    fontSize: "24px",
    fontWeight: "700",
    margin: "20px 0",
  },
  menu: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  menuItem: {
    display: "flex",
    alignItems: "center",
    padding: "12px",
    borderRadius: "10px",
    cursor: "pointer",
  },
  activeItem: {
    background: "#1a366f",
  },
  main: {
    flex: 1,
    padding: "30px",
  },
  contentSplit: {
    display: "grid",
    gridTemplateColumns: "1.3fr 1fr",
    gap: "18px",
    alignItems: "start",
  },
  headerRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
    flexWrap: "wrap",
    marginBottom: "12px",
  },
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    width: "100%",
    maxWidth: "720px",
  },
  headerActions: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  title: {
    marginBottom: "8px",
    color: "#11224d",
    fontSize: "44px",
    lineHeight: "110%",
  },
  searchBar: {
    marginBottom: 0,
    minWidth: "260px",
    flex: "0 1 360px",
  },
  searchInput: {
    width: "100%",
    maxWidth: "420px",
    padding: "12px 14px",
    borderRadius: "10px",
    border: "1px solid #d9dfeb",
    fontSize: "14px",
    outline: "none",
    backgroundColor: "#ffffff",
    color: "#11224d",
  },
  card: {
    background: "white",
    padding: "20px",
    borderRadius: "12px",
    boxShadow: "0 4px 14px rgba(0,0,0,0.06)",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  th: {
    textAlign: "left",
    padding: "12px",
    borderBottom: "1px solid #dfe5f0",
    color: "#11224d",
    fontSize: "14px",
  },
  td: {
    padding: "12px",
    borderBottom: "1px solid #eef2f7",
    color: "#33415c",
    fontSize: "14px",
  },
  row: {
    cursor: "pointer",
    transition: "background 0.15s, box-shadow 0.15s",
  },
  rowSelected: {
    background: "#eef3ff",
    boxShadow: "inset 2px 0 0 #1a366f",
  },
  badge: {
    display: "inline-block",
    padding: "6px 10px",
    borderRadius: "999px",
    fontSize: "12px",
    fontWeight: 600,
    letterSpacing: "0.02em",
  },
  badgeActive: {
    background: "#e7f6ec",
    color: "#1f7a39",
    border: "1px solid #c7e8d0",
  },
  badgeInactive: {
    background: "#f9eded",
    color: "#a12d2d",
    border: "1px solid #edcfcf",
  },
  primaryButton: {
    background: "#11224d",
    color: "white",
    border: "1px solid #11224d",
    borderRadius: "10px",
    padding: "10px 16px",
    fontWeight: 700,
  },
  secondaryButton: {
    background: "white",
    color: "#11224d",
    border: "1px solid #dfe5f0",
    borderRadius: "10px",
    padding: "10px 16px",
    fontWeight: 600,
  },
  primaryGhostButton: {
    background: "white",
    color: "#11224d",
    border: "1px solid #dfe5f0",
    borderRadius: "10px",
    padding: "8px 14px",
    fontWeight: 600,
  },
  dangerButton: {
    background: "#fff5f3",
    color: "#a12d2d",
    border: "1px solid #f2c8bc",
    borderRadius: "10px",
    padding: "10px 16px",
    fontWeight: 700,
  },
  mainHeader: {
    display: "flex",
    justifyContent: "flex-end",
    marginBottom: "8px",
  },
  editActions: {
    display: "flex",
    gap: "8px",
  },
  editablePanel: {
    border: "1px solid #eef2f7",
    borderRadius: "12px",
    padding: "14px",
    background: "#fafbfe",
  },
  editablePanelActive: {
    borderColor: "#c9d6ff",
    boxShadow: "0 0 0 2px rgba(17,34,77,0.08)",
  },
  detailCard: {
    background: "white",
    padding: "20px",
    borderRadius: "12px",
    boxShadow: "0 4px 14px rgba(0,0,0,0.06)",
    minHeight: "200px",
  },
  detailHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "14px",
  },
  detailTitle: {
    margin: 0,
    color: "#11224d",
    fontSize: "18px",
  },
  tabs: {
    display: "flex",
    gap: "8px",
    marginBottom: "16px",
  },
  tabButton: {
    padding: "8px 14px",
    borderRadius: "10px",
    border: "1px solid #dfe5f0",
    background: "#f7f9fb",
    color: "#11224d",
    cursor: "pointer",
    fontWeight: 600,
  },
  tabButtonActive: {
    background: "#11224d",
    color: "white",
    borderColor: "#11224d",
  },
  detailBody: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  detailField: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  detailLabel: {
    fontSize: "12px",
    color: "#6d7b98",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  detailValue: {
    fontSize: "15px",
    color: "#11224d",
    fontWeight: 600,
  },
  input: {
    padding: "10px 12px",
    borderRadius: "10px",
    border: "1px solid #dfe5f0",
    fontSize: "14px",
    color: "#11224d",
    background: "white",
  },
  toggleLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "14px",
    color: "#11224d",
  },
  checkbox: {
    width: "16px",
    height: "16px",
  },
  select: {
    padding: "10px 12px",
    borderRadius: "10px",
    border: "1px solid #dfe5f0",
    fontSize: "14px",
    color: "#11224d",
    background: "white",
  },
  relationsBody: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  relationsToolbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
    flexWrap: "wrap",
  },
  relationsToolbarText: {
    color: "#11224d",
    fontWeight: 600,
    fontSize: "14px",
  },
  relationsTableWrap: {
    overflowX: "auto",
  },
  relationsTable: {
    width: "100%",
    borderCollapse: "collapse",
  },
  relationFormPanel: {
    marginTop: "4px",
  },
  relationFormHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "10px",
    marginBottom: "12px",
    flexWrap: "wrap",
  },
  relationFormTitle: {
    margin: 0,
    color: "#11224d",
    fontSize: "16px",
  },
  relationFormMeta: {
    color: "#6d7b98",
    fontSize: "13px",
    fontWeight: 600,
  },
  relationFormGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "12px",
  },
  relationFormActions: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
    marginTop: "14px",
  },
  mutedText: {
    color: "#6d7b98",
  },
  successText: {
    color: "#1f7a39",
    fontWeight: 600,
    marginTop: "6px",
  },
  importResult: {
    background: "#f5fbf6",
    border: "1px solid #cde9d4",
    color: "#1f7a39",
    padding: "12px 14px",
    borderRadius: "10px",
    marginBottom: "12px",
    fontSize: "14px",
  },
  importResultError: {
    background: "#fdf3f0",
    border: "1px solid #f2c8bc",
    color: "#a12d2d",
    padding: "12px 14px",
    borderRadius: "10px",
    marginBottom: "12px",
    fontSize: "14px",
  },
  errorList: {
    margin: "8px 0 0",
    paddingLeft: "18px",
    color: "#a12d2d",
  },
  error: {
    color: "crimson",
  },
};
